<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameTestAutomationDemo.Vision\GameTestAutomationDemo.Vision.csproj" />
    <ProjectReference Include="..\GameTestAutomationDemo.Input\GameTestAutomationDemo.Input.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
